AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a misconfigured EC2 instance

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c55b159cbfafe1f0  # Replace with a suitable AMI ID
      InstanceType: t2.micro  # Underpowered instance type
      SecurityGroups:
        - Ref: InsecureSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          echo "Hello, World!" > index.html
          nohup python -m SimpleHTTPServer 80 &  # Running a web server without proper security
  InsecureSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all inbound traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
