---
AWSTemplateFormatVersion: "2010-09-09"
Description: "BAD"
Resources:
  S3Bucket:
    Type: "AWS::S3:Bucket"
  Properties:
    BucketName: "badbucket"
    PublicAccessBlockConfiguration:
    BlockPublicAcls: false
    BlockPublicPolicy: false
    IgnorePublicAcls: true
    RestrictPublicBuckets: false
    BucketEncryption:
      ServerSideEncryptionConfiguration:
      - BucketKeyEnabled: false
